### ISSUE TITLE
comby.min.js works, but not comby.js

### ISSUE THREAD

**Issue by d4hines** [comby-tools/comby.js#2]
I get the following error:
```
❯ node ./test/example-rewrite-rule.js 
/home/d4hines/repos/comby.js/js/comby.js:906
     {if(s.length < 24)
           ^

TypeError: Cannot read property 'length' of undefined
    at jsoo_is_ascii (/home/d4hines/repos/comby.js/js/comby.js:906:12)
    at caml_bytes_of_utf16_jsstring (/home/d4hines/repos/comby.js/js/comby.js:2219:12)
    at caml_string_of_jsstring (/home/d4hines/repos/comby.js/js/comby.js:2222:14)
    at rewrite$1 (/home/d4hines/repos/comby.js/js/comby.js:118189:29)
    at Object.<anonymous> (/home/d4hines/repos/comby.js/test/example-rewrite-rule.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

But when I swap the `require` in the first line of that file for `../js/comby.min.js`, it works fine.

(I know this is unfinished work so no pressure - just snooping around and noticed this).

**Comment by rvantonder** [comment]
maybe works now, revamped it
